version = 0.1

[default.deploy.parameters]
stack_name = "arcline-server"
resolve_s3 = true
s3_prefix = "arcline-server"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ImageUri=\"508767886604.dkr.ecr.us-east-1.amazonaws.com/arcline-server\" Domain=\"arcline.jasonrundell.com\" SupabaseUrl=\"https://nnbepmerodenobxteusj.supabase.co\" SSLCertificateArn=\"\""
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
